/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedUtilizationRouteImport } from './routes/_authenticated/utilization'
import { Route as AuthenticatedSpreadsRouteImport } from './routes/_authenticated/spreads'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedOutagesRouteImport } from './routes/_authenticated/outages'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedFlowsRouteImport } from './routes/_authenticated/flows'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDanubeRouteImport } from './routes/_authenticated/danube'
import { Route as AuthenticatedCbcRouteImport } from './routes/_authenticated/cbc'
import { Route as AuthenticatedCapacityRouteImport } from './routes/_authenticated/capacity'
import { Route as AuthenticatedBalanceRouteImport } from './routes/_authenticated/balance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUtilizationRoute =
  AuthenticatedUtilizationRouteImport.update({
    id: '/utilization',
    path: '/utilization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpreadsRoute = AuthenticatedSpreadsRouteImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutagesRoute = AuthenticatedOutagesRouteImport.update({
  id: '/outages',
  path: '/outages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlowsRoute = AuthenticatedFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDanubeRoute = AuthenticatedDanubeRouteImport.update({
  id: '/danube',
  path: '/danube',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCbcRoute = AuthenticatedCbcRouteImport.update({
  id: '/cbc',
  path: '/cbc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCapacityRoute = AuthenticatedCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBalanceRoute = AuthenticatedBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/capacity': typeof AuthenticatedCapacityRoute
  '/cbc': typeof AuthenticatedCbcRoute
  '/danube': typeof AuthenticatedDanubeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flows': typeof AuthenticatedFlowsRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/map': typeof AuthenticatedMapRoute
  '/outages': typeof AuthenticatedOutagesRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spreads': typeof AuthenticatedSpreadsRoute
  '/utilization': typeof AuthenticatedUtilizationRoute
  '/weather': typeof AuthenticatedWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/capacity': typeof AuthenticatedCapacityRoute
  '/cbc': typeof AuthenticatedCbcRoute
  '/danube': typeof AuthenticatedDanubeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flows': typeof AuthenticatedFlowsRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/map': typeof AuthenticatedMapRoute
  '/outages': typeof AuthenticatedOutagesRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spreads': typeof AuthenticatedSpreadsRoute
  '/utilization': typeof AuthenticatedUtilizationRoute
  '/weather': typeof AuthenticatedWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/balance': typeof AuthenticatedBalanceRoute
  '/_authenticated/capacity': typeof AuthenticatedCapacityRoute
  '/_authenticated/cbc': typeof AuthenticatedCbcRoute
  '/_authenticated/danube': typeof AuthenticatedDanubeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/flows': typeof AuthenticatedFlowsRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/outages': typeof AuthenticatedOutagesRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/spreads': typeof AuthenticatedSpreadsRoute
  '/_authenticated/utilization': typeof AuthenticatedUtilizationRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/balance'
    | '/capacity'
    | '/cbc'
    | '/danube'
    | '/dashboard'
    | '/flows'
    | '/forecast'
    | '/map'
    | '/outages'
    | '/prices'
    | '/settings'
    | '/spreads'
    | '/utilization'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/balance'
    | '/capacity'
    | '/cbc'
    | '/danube'
    | '/dashboard'
    | '/flows'
    | '/forecast'
    | '/map'
    | '/outages'
    | '/prices'
    | '/settings'
    | '/spreads'
    | '/utilization'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/balance'
    | '/_authenticated/capacity'
    | '/_authenticated/cbc'
    | '/_authenticated/danube'
    | '/_authenticated/dashboard'
    | '/_authenticated/flows'
    | '/_authenticated/forecast'
    | '/_authenticated/map'
    | '/_authenticated/outages'
    | '/_authenticated/prices'
    | '/_authenticated/settings'
    | '/_authenticated/spreads'
    | '/_authenticated/utilization'
    | '/_authenticated/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/utilization': {
      id: '/_authenticated/utilization'
      path: '/utilization'
      fullPath: '/utilization'
      preLoaderRoute: typeof AuthenticatedUtilizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spreads': {
      id: '/_authenticated/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof AuthenticatedSpreadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outages': {
      id: '/_authenticated/outages'
      path: '/outages'
      fullPath: '/outages'
      preLoaderRoute: typeof AuthenticatedOutagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flows': {
      id: '/_authenticated/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AuthenticatedFlowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/danube': {
      id: '/_authenticated/danube'
      path: '/danube'
      fullPath: '/danube'
      preLoaderRoute: typeof AuthenticatedDanubeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cbc': {
      id: '/_authenticated/cbc'
      path: '/cbc'
      fullPath: '/cbc'
      preLoaderRoute: typeof AuthenticatedCbcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capacity': {
      id: '/_authenticated/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof AuthenticatedCapacityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/balance': {
      id: '/_authenticated/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthenticatedBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBalanceRoute: typeof AuthenticatedBalanceRoute
  AuthenticatedCapacityRoute: typeof AuthenticatedCapacityRoute
  AuthenticatedCbcRoute: typeof AuthenticatedCbcRoute
  AuthenticatedDanubeRoute: typeof AuthenticatedDanubeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFlowsRoute: typeof AuthenticatedFlowsRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedOutagesRoute: typeof AuthenticatedOutagesRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpreadsRoute: typeof AuthenticatedSpreadsRoute
  AuthenticatedUtilizationRoute: typeof AuthenticatedUtilizationRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBalanceRoute: AuthenticatedBalanceRoute,
  AuthenticatedCapacityRoute: AuthenticatedCapacityRoute,
  AuthenticatedCbcRoute: AuthenticatedCbcRoute,
  AuthenticatedDanubeRoute: AuthenticatedDanubeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFlowsRoute: AuthenticatedFlowsRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedOutagesRoute: AuthenticatedOutagesRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpreadsRoute: AuthenticatedSpreadsRoute,
  AuthenticatedUtilizationRoute: AuthenticatedUtilizationRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
